# ────────────────────────────────────────────────
#  SITE BASICS
# ────────────────────────────────────────────────
locale            : "en-US"
title             : "Molecular Physics Simulation Group"
title_separator   : "-"
description       : "Computational theorist exploring molecular-scale transport for energy-efficient devices."
url               : "https://yechan-noh.github.io"   # production URL
baseurl           : "/MMSL"                          # GitHub Pages project repo
repository        : "Yechan-Noh/MMSL.github.io"
remote_theme      : "mmistakes/minimal-mistakes"


# ────────────────────────────────────────────────
#  AUTHOR PROFILE (sidebar + JSON-LD)
# ────────────────────────────────────────────────
author:
  name        : "Yechan Noh"
  avatar      : "Yechan_photo.png"
  bio         : "Postdoctoral Fellow · Notre Dame // Molecular transport, iontronics, neuromorphic AI."
  location    : "South Bend, USA"
  email       : "ynoh@nd.edu"
  googlescholar : "https://scholar.google.com/citations?user=0zdqbtIAAAAJ"
  orcid         : "https://orcid.org/0000-0003-1688-4907"
  linkedin      : "yechan-noh-phd-421906155"

# ────────────────────────────────────────────────
#  PUBLICATION CATEGORIES
# ────────────────────────────────────────────────
publication_category:
  manuscripts : { title: "Journal Articles" }
  conferences : { title: "Conference Papers" }
  books       : { title: "Books" }

# ────────────────────────────────────────────────
#  COLLECTIONS
# ────────────────────────────────────────────────
collections:
  teaching   : { output: true, permalink: /:collection/:path/ }
  publications: { output: true, permalink: /:collection/:path/ }
  portfolio  : { output: true, permalink: /:collection/:path/ }
  talks      : { output: true, permalink: /:collection/:path/ }

# ────────────────────────────────────────────────
#  DEFAULT FRONT-MATTER
# ────────────────────────────────────────────────
defaults:
  - scope: { path: "", type: pages }
    values:
      layout         : single
      author_profile : true
  - scope: { path: "", type: posts }
    values:
      layout         : single
      author_profile : true
      read_time      : true
      comments       : false
      share          : true

# ────────────────────────────────────────────────
#  UI OPTIONS
# ────────────────────────────────────────────────
breadcrumbs      : false
future           : true
read_more        : "disabled"
teaser           :                         # fallback post image (in /images/)
syntax_highlighter : rouge
minimal_mistakes_skin : "default"          # “air”, “dark”, “sunrise”, etc.

# ────────────────────────────────────────────────
#  SEO & SOCIAL
# ────────────────────────────────────────────────
social:
  type : Person
  name : "Yechan Noh"
  links:
    - "https://scholar.google.com/citations?user=0zdqbtIAAAAJ"
    - "https://www.linkedin.com/in/yechan-noh-phd-421906155/"

og_image         : "/images/site-share.png"  # ⚑ optional OG image
og_description   : "MPSG · Computational molecular physics research."

# ────────────────────────────────────────────────
#  ANALYTICS  (Google Analytics 4 — replace ID)
# ────────────────────────────────────────────────
analytics:
  provider        : google-analytics-4
  google:
    tracking_id   : "G-XXXXXXX"            # ⚑ replace with your GA4 ID

# ────────────────────────────────────────────────
#  SASS
# ────────────────────────────────────────────────
sass:
  sass_dir : _sass
  style    : compressed

# ────────────────────────────────────────────────
#  PLUGINS
# ────────────────────────────────────────────────
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from
  - jekyll-gist

# whitelist for GitHub-Pages safe mode
whitelist: [jekyll-feed, jekyll-sitemap, jekyll-paginate, jemoji, jekyll-redirect-from, jekyll-gist]

# ────────────────────────────────────────────────
#  MISC
# ────────────────────────────────────────────────
markdown        : kramdown
highlighter     : rouge
permalink       : /:categories/:title/
timezone        : America/Indiana/Indianapolis   # ⚑ adjust if needed
include         : [".htaccess", "_pages", "files"]
exclude         :
  - node_modules
  - vendor
  - README
compress_html:  { clippings: all }
